### ISSUE TITLE
API Changed again ????

### ISSUE THREAD

**Issue by ghhausi** [platysma/vienna-smartmeter#176]
Hi guys - how is it going with Vienna-smartmeter on your side ?
Cloud it be that there is another (more severe) API-change
I saw e.g. for "profile" the python program sends
'https://service.wienernetze.at/rest/smp/1.0/w/user/profile' <-- this returns a **"500"**
the Web-portal uses **https://service.wienernetze.at/sm/api/user/profile** 

Now getting data:
URL in python https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/messdaten/1200795740/AT0010000000000000001000006898434/verbrauch?dateFrom=24-05-08T00%3A00%3A00.000Z&dateTo=2024-05-09T14%3A52%3A01.157Z&period=DAY&accumulate=False&offset=0&dayViewResolution=QUARTER-HOUR
**should be something like:**
https://service.wienernetze.at/sm/api/user/messwerte/bewegungsdaten?geschaeftspartner=1200795740&zaehlpunktnummer=AT0010000000000000001000006898434&rolle=V002&zeitpunktVon=2024-05-07T22%3A00%3A00.000Z&zeitpunktBis=2024-05-08T21%3A59%3A59.999Z&aggregat=NONE

Could that be ? Or am I missing something ?

I just had a short view looking into the portal - comparing with the python program

Thanks
Hausi

**Comment by spinnaker1** [comment]
I confirm API error.

`Traceback (most recent call last):
  File "/app/./main.py", line 68, in <module>
    verbrauch_data = api.verbrauch(date_to_fetch)['values']
  File "/app/viennasmartmeter.py", line 208, in verbrauch
    endpoint = "messdaten/{0}/{1}/verbrauch".format(self.customerid(),zaehlpunkt)
  File "/app/viennasmartmeter.py", line 154, in customerid
    return self._call_api_wn("w/user/profile")["defaultGeschaeftspartnerRegistration"]["geschaeftspartner"]
KeyError: 'defaultGeschaeftspartnerRegistration'`

**Comment by ghhausi** [comment]
**WORKS AGAIN:**
based on the client.py from "fleinze" is changed line 239 (**def profile(self)**) to:
        **return self._call_api_wn("/user/profile", base_url="https://service.wienernetze.at/sm/api")**
the rest seems to work.
please verify and merge back.
regards
Gerhard

**Comment by chfritsch** [comment]
I can confirm this fix works as expected

**Comment by xaver95** [comment]
I can confrim. Switching to fleinze's open PR fixed the problem for me. (https://github.com/fleinze/vienna-smartmeter).
